# Generated by Django 4.2.7 on 2024-05-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="game_type",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
